version: '3'

services:
  mariadb:
    container_name: mariadb			# Le nom du container, oui vraiment.
    networks:
      - inception            			# à quel network il appartient
    build: 
      context: requirements/mariadb 	# ou se trouve son Dockerfile
      dockerfile: Dockerfile			# le nom du Dockerfile ?!
    env_file: .env                  # le fichier d'environnement pour transmettre les variables
    volumes:                        # Voir plus bas
      - mariadb:/var/lib/mysql
    restart: unless-stopped         # redémarre tant qu'il n'est pas stoppé 
    expose:                         # le port à exposer
      - "3306"

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/frgojard/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/frgojard/data/mysql'
  
networks:
  inception:
    driver: bridge
